//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnicalTesEntities : DbContext
    {
        public TechnicalTesEntities()
            : base("name=TechnicalTesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ms_storage_location> ms_storage_location { get; set; }
        public virtual DbSet<ms_user> ms_user { get; set; }
        public virtual DbSet<tr_bpkb> tr_bpkb { get; set; }
    }
}
