//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_user
    {
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
